# Generated by Django 4.2 on 2026-07-07 13:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('experience_required', models.CharField(help_text='e.g. 3-5 years', max_length=100)),
                ('education_required', models.TextField(help_text="e.g. Bachelor's degree in CS")),
                ('skills_required', models.TextField(help_text='Comma-separated skills list, e.g. python, django, react')),
                ('description', models.TextField()),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('candidate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('extracted_skills', models.TextField(blank=True, help_text='Comma-separated skills extracted', null=True)),
                ('experience_text', models.TextField(blank=True, null=True)),
                ('education_text', models.TextField(blank=True, null=True)),
                ('resume_text', models.TextField(blank=True, null=True)),
                ('skills_match_score', models.FloatField(default=0.0)),
                ('experience_match_score', models.FloatField(default=0.0)),
                ('education_match_score', models.FloatField(default=0.0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='screener_app.jobdescription')),
            ],
        ),
    ]
